version: '3.8'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: crypto_purchase_db
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: .
    command: gunicorn crypto_purchase.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A crypto_purchase worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A crypto_purchase beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis